// Top-level build file where you can add configuration options common to all sub-projects/modules.

buildscript {

    repositories {
        google()
        jcenter()
        maven { url 'https://jitpack.io' }
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:7.4.2'
        classpath 'com.google.gms:google-services:4.3.15'
        classpath 'com.google.firebase:firebase-crashlytics-gradle:2.9.9'
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:1.8.10"
    }
}

allprojects {
    repositories {
        google()
        jcenter()
        maven { url 'https://jitpack.io' }
    }
}

task clean(type: Delete) {
    delete rootProject.buildDir
}

ext {
    // Kotlin
    kotlin_version = '1.8.10'
    // App dependencies
    supportLibraryVersion = '27.1.1'
    flexboxVersion = '0.2.5'
    rxJavaVersion = '2.0.1'
    constraintLayoutVersion = '1.1.0'
    roomVersion = '1.1.0'
    calligraphyVersion = '2.2.0'
    guavaVersion = '18.0'
    daggerVersion = '2.48.1'  //'2.33'
    sugarVersion = '1.4'
    glideVersion = '4.12.0'
    recyclerViewVersion = '25.1.1'
    superrecyclerViewVersion = '1.1.4'
    butterKnifeVersion = '10.2.3'
    retrofitVersion = '2.3.0'
    converterGsonVersion = '2.0.0'
    okhttpVersion = '3.6.0'
    gsonVersion = '2.8.0'
    junitVersion = '4.13.2'
    espressoVersion = '2.2.2'
}
